### ISSUE TITLE
Setup CD on dirdapi.chaz.pro

### ISSUE THREAD

**Issue by shadonovitch** [shadonovitch/dird-project-back#15]
It would be cool to automatically deploy to dirdapi.chaz.pro on updates on master branch.  

From circleci docs: 
```yml
# Deploy via SSH
version: 2
jobs:
  build:
    #...
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "<remote deploy command>"
``` 
Tasklist: 

- [x] Create a circleci user and  its own sshkey
- [x] Upload key to circleci
- [x] Update current .circleci/config.yml
- [x] Write and test docker deploy shell script for DirdAPI
